module.exports = {
  spelldata: [
    {
      "spellName": "None",
      "chaosRating": 0,
      "castChance": 0,
      "castRange": 0,
      "castPriority": 0,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 0,
      "spellFunction": "cast_disbelieve",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Disbelieve",
      "chaosRating": 0,
      "castChance": 10,
      "castRange": 20,
      "castPriority": 0,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 0,
      "spellFunction": "cast_disbelieve",
      "description": "Dispels an illusory creature",
      "flags": ""
    },
    {
      "spellName": "Meditate",
      "chaosRating": 0,
      "castChance": 1,
      "castRange": 0,
      "castPriority": 5,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 0,
      "spellFunction": "cast_meditate",
      "description": "The wizard tries to think of a new spell but misses a movement turn",
      "flags": "NEW_FEATURE"
    },
    {
      "spellName": "King Cobra",
      "chaosRating": 1,
      "castChance": 10,
      "castRange": 1,
      "castPriority": 18,
      "palette": 0,
      "combat": 4,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 1,
      "movement": 1,
      "manvr": 6,
      "magicRes": 1,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Dire Wolf",
      "chaosRating": -1,
      "castChance": 9,
      "castRange": 1,
      "castPriority": 18,
      "palette": 1,
      "combat": 3,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 2,
      "movement": 3,
      "manvr": 7,
      "magicRes": 2,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Goblin",
      "chaosRating": -1,
      "castChance": 9,
      "castRange": 1,
      "castPriority": 18,
      "palette": 6,
      "combat": 2,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 4,
      "movement": 1,
      "manvr": 4,
      "magicRes": 4,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Crocodile",
      "chaosRating": 0,
      "castChance": 8,
      "castRange": 1,
      "castPriority": 18,
      "palette": 0,
      "combat": 5,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 6,
      "movement": 1,
      "manvr": 2,
      "magicRes": 2,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Troll",
      "chaosRating": -1,
      "castChance": 6,
      "castRange": 1,
      "castPriority": 18,
      "palette": 1,
      "combat": 4,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 8,
      "movement": 1,
      "manvr": 1,
      "magicRes": 4,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": "NEW_FEATURE"
    },
    {
      "spellName": "Faun",
      "chaosRating": -1,
      "castChance": 8,
      "castRange": 1,
      "castPriority": 18,
      "palette": 3,
      "combat": 3,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 2,
      "movement": 1,
      "manvr": 7,
      "magicRes": 8,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Lion",
      "chaosRating": 1,
      "castChance": 6,
      "castRange": 1,
      "castPriority": 18,
      "palette": 2,
      "combat": 6,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 4,
      "movement": 4,
      "manvr": 8,
      "magicRes": 3,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Elf",
      "chaosRating": 2,
      "castChance": 7,
      "castRange": 1,
      "castPriority": 18,
      "palette": 0,
      "combat": 1,
      "rangedCombat": 2,
      "rangedCombatRange": 6,
      "defence": 2,
      "movement": 1,
      "manvr": 5,
      "magicRes": 7,
      "frequency": 2,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Orc",
      "chaosRating": -1,
      "castChance": 10,
      "castRange": 1,
      "castPriority": 18,
      "palette": 3,
      "combat": 2,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 1,
      "movement": 1,
      "manvr": 4,
      "magicRes": 4,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Bear",
      "chaosRating": 1,
      "castChance": 6,
      "castRange": 1,
      "castPriority": 18,
      "palette": 3,
      "combat": 6,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 7,
      "movement": 2,
      "manvr": 6,
      "magicRes": 2,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Gorilla",
      "chaosRating": 0,
      "castChance": 7,
      "castRange": 1,
      "castPriority": 18,
      "palette": 7,
      "combat": 6,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 5,
      "movement": 1,
      "manvr": 4,
      "magicRes": 2,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Ogre",
      "chaosRating": -1,
      "castChance": 7,
      "castRange": 1,
      "castPriority": 18,
      "palette": 4,
      "combat": 4,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 7,
      "movement": 1,
      "manvr": 3,
      "magicRes": 6,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Hydra",
      "chaosRating": -1,
      "castChance": 5,
      "castRange": 1,
      "castPriority": 18,
      "palette": 0,
      "combat": 7,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 8,
      "movement": 1,
      "manvr": 4,
      "magicRes": 6,
      "frequency": 2,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Giant Rat",
      "chaosRating": 0,
      "castChance": 10,
      "castRange": 1,
      "castPriority": 18,
      "palette": 1,
      "combat": 1,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 1,
      "movement": 3,
      "manvr": 8,
      "magicRes": 2,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Giant",
      "chaosRating": 1,
      "castChance": 4,
      "castRange": 1,
      "castPriority": 18,
      "palette": 6,
      "combat": 9,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 7,
      "movement": 2,
      "manvr": 6,
      "magicRes": 5,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Horse",
      "chaosRating": 1,
      "castChance": 9,
      "castRange": 1,
      "castPriority": 18,
      "palette": 3,
      "combat": 1,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 3,
      "movement": 4,
      "manvr": 8,
      "magicRes": 1,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Unicorn",
      "chaosRating": 2,
      "castChance": 6,
      "castRange": 1,
      "castPriority": 18,
      "palette": 7,
      "combat": 5,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 4,
      "movement": 4,
      "manvr": 9,
      "magicRes": 7,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Centaur",
      "chaosRating": 1,
      "castChance": 7,
      "castRange": 1,
      "castPriority": 18,
      "palette": 3,
      "combat": 1,
      "rangedCombat": 2,
      "rangedCombatRange": 4,
      "defence": 3,
      "movement": 4,
      "manvr": 5,
      "magicRes": 5,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Pegasus",
      "chaosRating": 2,
      "castChance": 7,
      "castRange": 1,
      "castPriority": 18,
      "palette": 1,
      "combat": 2,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 4,
      "movement": 5,
      "manvr": 6,
      "magicRes": 7,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Gryphon",
      "chaosRating": 1,
      "castChance": 6,
      "castRange": 1,
      "castPriority": 18,
      "palette": 1,
      "combat": 3,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 5,
      "movement": 5,
      "manvr": 5,
      "magicRes": 6,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Manticore",
      "chaosRating": -1,
      "castChance": 4,
      "castRange": 1,
      "castPriority": 18,
      "palette": 2,
      "combat": 3,
      "rangedCombat": 1,
      "rangedCombatRange": 3,
      "defence": 6,
      "movement": 5,
      "manvr": 6,
      "magicRes": 8,
      "frequency": 2,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Bat",
      "chaosRating": -1,
      "castChance": 8,
      "castRange": 1,
      "castPriority": 18,
      "palette": 1,
      "combat": 1,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 1,
      "movement": 5,
      "manvr": 9,
      "magicRes": 4,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Green Dragon",
      "chaosRating": -1,
      "castChance": 2,
      "castRange": 1,
      "castPriority": 18,
      "palette": 0,
      "combat": 5,
      "rangedCombat": 4,
      "rangedCombatRange": 6,
      "defence": 8,
      "movement": 3,
      "manvr": 4,
      "magicRes": 4,
      "frequency": 2,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Red Dragon",
      "chaosRating": -2,
      "castChance": 1,
      "castRange": 1,
      "castPriority": 18,
      "palette": 4,
      "combat": 7,
      "rangedCombat": 3,
      "rangedCombatRange": 5,
      "defence": 9,
      "movement": 3,
      "manvr": 4,
      "magicRes": 5,
      "frequency": 2,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Golden Dragon",
      "chaosRating": 2,
      "castChance": 2,
      "castRange": 1,
      "castPriority": 18,
      "palette": 2,
      "combat": 9,
      "rangedCombat": 5,
      "rangedCombatRange": 4,
      "defence": 9,
      "movement": 3,
      "manvr": 5,
      "magicRes": 5,
      "frequency": 1,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Harpy",
      "chaosRating": -1,
      "castChance": 7,
      "castRange": 1,
      "castPriority": 18,
      "palette": 1,
      "combat": 4,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 2,
      "movement": 5,
      "manvr": 8,
      "magicRes": 5,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Eagle",
      "chaosRating": 1,
      "castChance": 7,
      "castRange": 1,
      "castPriority": 18,
      "palette": 2,
      "combat": 3,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 3,
      "movement": 6,
      "manvr": 8,
      "magicRes": 2,
      "frequency": 2,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Vampire",
      "chaosRating": -2,
      "castChance": 2,
      "castRange": 1,
      "castPriority": 18,
      "palette": 1,
      "combat": 6,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 8,
      "movement": 4,
      "manvr": 6,
      "magicRes": 5,
      "frequency": 1,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Ghost",
      "chaosRating": -1,
      "castChance": 5,
      "castRange": 1,
      "castPriority": 18,
      "palette": 4,
      "combat": 1,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 3,
      "movement": 2,
      "manvr": 9,
      "magicRes": 6,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Spectre",
      "chaosRating": -1,
      "castChance": 6,
      "castRange": 1,
      "castPriority": 18,
      "palette": 7,
      "combat": 4,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 2,
      "movement": 1,
      "manvr": 6,
      "magicRes": 4,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Wraith",
      "chaosRating": -1,
      "castChance": 6,
      "castRange": 1,
      "castPriority": 18,
      "palette": 5,
      "combat": 5,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 5,
      "movement": 2,
      "manvr": 4,
      "magicRes": 5,
      "frequency": 2,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Skeleton",
      "chaosRating": -1,
      "castChance": 7,
      "castRange": 1,
      "castPriority": 18,
      "palette": 4,
      "combat": 3,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 2,
      "movement": 1,
      "manvr": 3,
      "magicRes": 4,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Zombie",
      "chaosRating": -1,
      "castChance": 9,
      "castRange": 1,
      "castPriority": 18,
      "palette": 7,
      "combat": 1,
      "rangedCombat": 0,
      "rangedCombatRange": 0,
      "defence": 1,
      "movement": 1,
      "manvr": 2,
      "magicRes": 3,
      "frequency": 3,
      "spellFunction": "cast_creature",
      "description": "",
      "flags": ""
    },
    {
      "spellName": "Gooey Blob",
      "chaosRating": -1,
      "castChance": 9,
      "castRange": 6,
      "castPriority": 18,
      "palette": 0,
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 3,
      "spellFunction": "cast_fire_goo",
      "description": "Spreads and suffocates but may be harmed",
      "flags": ""
    },
    {
      "spellName": "Magic Fire",
      "chaosRating": -1,
      "castChance": 8,
      "castRange": 6,
      "castPriority": 18,
      "palette": 4,
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 2,
      "spellFunction": "cast_fire_goo",
      "description": "Unstoppable fire that spreads and burns",
      "flags": ""
    },
    {
      "spellName": "Magic Wood",
      "chaosRating": 1,
      "castChance": 8,
      "castRange": 8,
      "castPriority": 17,
      "palette": 8,
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_trees_castles",
      "description": "Up to 8 trees are created with new spells hidden in their branches",
      "flags": ""
    },
    {
      "spellName": "Shadow Wood",
      "chaosRating": -1,
      "castChance": 4,
      "castRange": 8,
      "castPriority": 18,
      "palette": 5,
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_trees_castles",
      "description": "Creates up to 8 dark sentries with razor sharp boughs",
      "flags": ""
    },
    {
      "spellName": "Magic Castle",
      "chaosRating": 1,
      "castChance": 6,
      "castRange": 8,
      "castPriority": 23,
      "palette": 5,
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_trees_castles",
      "description": "A wizard can hide in this fortress and be protected from harm",
      "flags": ""
    },
    {
      "spellName": "Dark Citadel",
      "chaosRating": -1,
      "castChance": 6,
      "castRange": 8,
      "castPriority": 23,
      "palette": 5,
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_trees_castles",
      "description": "A wizard can hide in this fortress and be protected from harm",
      "flags": ""
    },
    {
      "spellName": "Wall",
      "chaosRating": 0,
      "castChance": 8,
      "castRange": 6,
      "castPriority": 12,
      "palette": 3,
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 2,
      "spellFunction": "cast_wall",
      "description": "Up to 4 brick walls that block spells and ranged attacks",
      "flags": ""
    },
    {
      "spellName": "Magic Bolt",
      "chaosRating": 0,
      "castChance": 10,
      "castRange": 6,
      "castPriority": 18,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 2,
      "spellFunction": "cast_magic_missile",
      "description": "Weak long range magical attack",
      "flags": ""
    },
    {
      "spellName": "Blind",
      "chaosRating": -1,
      "castChance": 10,
      "castRange": 6,
      "castPriority": 18,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_magic_missile",
      "description": "A blinded creature moves slowly and loses attack power",
      "flags": "NEW_FEATURE"
    },
    {
      "spellName": "Lightning",
      "chaosRating": 0,
      "castChance": 10,
      "castRange": 4,
      "castPriority": 18,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 2,
      "spellFunction": "cast_magic_missile",
      "description": "Strong magical attack with a short range",
      "flags": ""
    },
    {
      "spellName": "Magic Sleep",
      "chaosRating": 1,
      "castChance": 10,
      "castRange": 6,
      "castPriority": 18,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_magic_missile",
      "description": "A sleeping creature cannot move or defend itself",
      "flags": "NEW_FEATURE"
    },
    {
      "spellName": "Vengeance",
      "chaosRating": -1,
      "castChance": 8,
      "castRange": 20,
      "castPriority": 12,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_justice",
      "description": "1 chance to destroy a creature or all of a wizard's creatures",
      "flags": ""
    },
    {
      "spellName": "Justice",
      "chaosRating": 1,
      "castChance": 8,
      "castRange": 20,
      "castPriority": 12,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_justice",
      "description": "1 chance to destroy a creature or all of a wizard's creatures",
      "flags": ""
    },
    {
      "spellName": "Dark Power",
      "chaosRating": -2,
      "castChance": 5,
      "castRange": 20,
      "castPriority": 11,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_justice",
      "description": "3 chances to destroy a creature or all of a wizard's creatures",
      "flags": ""
    },
    {
      "spellName": "Decree",
      "chaosRating": 2,
      "castChance": 5,
      "castRange": 20,
      "castPriority": 11,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_justice",
      "description": "3 chances to destroy a creature or all of a wizard's creatures",
      "flags": ""
    },
    {
      "spellName": "Magic Shield",
      "chaosRating": 1,
      "castChance": 7,
      "castRange": 0,
      "castPriority": 23,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_magic_shield",
      "description": "Increases a wizard's defence",
      "flags": ""
    },
    {
      "spellName": "Magic Armour",
      "chaosRating": 1,
      "castChance": 4,
      "castRange": 0,
      "castPriority": 23,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_magic_armour",
      "description": "Greatly increases a wizard's defence",
      "flags": ""
    },
    {
      "spellName": "Magic Sword",
      "chaosRating": 1,
      "castChance": 4,
      "castRange": 0,
      "castPriority": 16,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_magic_sword",
      "description": "Greatly increases a wizard's combat",
      "flags": ""
    },
    {
      "spellName": "Magic Knife",
      "chaosRating": 1,
      "castChance": 7,
      "castRange": 0,
      "castPriority": 16,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_magic_knife",
      "description": "Increases a wizard's combat",
      "flags": ""
    },
    {
      "spellName": "Magic Bow",
      "chaosRating": 1,
      "castChance": 5,
      "castRange": 0,
      "castPriority": 17,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_magic_bow",
      "description": "Grants ranged combat for wizards",
      "flags": ""
    },
    {
      "spellName": "Magic Wings",
      "chaosRating": 0,
      "castChance": 5,
      "castRange": 0,
      "castPriority": 14,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_magic_wings",
      "description": "Allows a wizard to fly",
      "flags": ""
    },
    {
      "spellName": "Law 1",
      "chaosRating": 2,
      "castChance": 8,
      "castRange": 0,
      "castPriority": 5,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_chaos_law",
      "description": "Alters the balance of the universe",
      "flags": ""
    },
    {
      "spellName": "Law 2",
      "chaosRating": 4,
      "castChance": 6,
      "castRange": 0,
      "castPriority": 6,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_chaos_law",
      "description": "Greatly alters the balance of the universe",
      "flags": ""
    },
    {
      "spellName": "Chaos 1",
      "chaosRating": -2,
      "castChance": 8,
      "castRange": 0,
      "castPriority": 5,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_chaos_law",
      "description": "Alters the balance of the universe",
      "flags": ""
    },
    {
      "spellName": "Chaos 2",
      "chaosRating": -4,
      "castChance": 6,
      "castRange": 0,
      "castPriority": 6,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_chaos_law",
      "description": "Greatly alters the balance of the universe",
      "flags": ""
    },
    {
      "spellName": "Shadow Form",
      "chaosRating": 0,
      "castChance": 8,
      "castRange": 0,
      "castPriority": 18,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_shadow_form",
      "description": "Wizard becomes fleet of foot until they engage in combat",
      "flags": ""
    },
    {
      "spellName": "Subversion",
      "chaosRating": 0,
      "castChance": 10,
      "castRange": 7,
      "castPriority": 18,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_subversion",
      "description": "Take control of an enemy creature",
      "flags": ""
    },
    {
      "spellName": "Mutation",
      "chaosRating": 0,
      "castChance": 10,
      "castRange": 7,
      "castPriority": 18,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_subversion",
      "description": "Changes a creature into a random new form",
      "flags": "NEW_FEATURE"
    },
    {
      "spellName": "Raise Dead",
      "chaosRating": -1,
      "castChance": 5,
      "castRange": 4,
      "castPriority": 18,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_raise_dead",
      "description": "Reanimate a dead creature",
      "flags": ""
    },
    {
      "spellName": "Turmoil",
      "chaosRating": -1,
      "castChance": 5,
      "castRange": 0,
      "castPriority": 17,
      "palette": "",
      "combat": "",
      "rangedCombat": "",
      "rangedCombatRange": "",
      "defence": "",
      "movement": "",
      "manvr": "",
      "magicRes": "",
      "frequency": 1,
      "spellFunction": "cast_turmoil",
      "description": "Randomly move all creatures and objects to new locations",
      "flags": ""
    }
  ]
};